name: solr-app
disk: 1024
type: php:7.0
relationships:
  "solr": "solrservice:solr"
web:
  locations:
    '/':
      root: web
      passthru: '/index.php'
mounts:
  "log": "shared:files/log"
hooks:
  deploy:
    touch log/update.log